#
# Makefile for installing the mingw32 version of the SDL2_ttf library

CROSS_PATH := /usr/local/cross-tools
ARCHITECTURES := x86_64-w64-mingw32

build:
	@echo noop

install:
	cp -R x86_64-w64_mingw32 /usr
