[[Monster]]
Name = "Rat"
Description = "A large rat. It is trying not to be seen."
Glyph = "r"
Color = [255, 255, 0]
Level = 1
HP = 2

[[Monster]]
Name = "Goblin"
Description = "A hungry little goblin."
Glyph = "g"
Color = [0, 255, 0] 
Level = 1
HP = 5

[[Monster]]
Name = "Orc"
Description = "A furious orc."
Glyph = "o"
Color = [25, 225, 10] 
Level = 3
HP =  14

[[Monster]]
Name = "Wolf"
Description = "A starving wolf."
Glyph = "w"
Color = [200, 200, 200]
Level = 1
HP = 7

[[Monster]]
Name = "Troll"
Description = "A huge lumbering troll."
Glyph = "T"
Color = [0, 255, 0]
Level = 5
HP = 44